export const siteDescription =
  "Waves Studio delivers web development, mobile app development, desktop software, UI/UX design, graphic design, branding, and digital marketing services for startups, brands, and growing businesses.";

export const siteName = "Waves Studio";
export const defaultShareImagePath = "/codelegendlogo.jpg";

export const siteKeywords = [
  "Waves Studio",
  "software development company",
  "software house",
  "digital agency",
  "digital services",
  "custom software development",
  "web development",
  "website development",
  "website design",
  "custom website",
  "corporate website",
  "business website",
  "landing page design",
  "landing page development",
  "e-commerce development",
  "online store development",
  "ecommerce website",
  "web application development",
  "custom web application",
  "SaaS development",
  "dashboard development",
  "admin dashboard",
  "frontend development",
  "backend development",
  "full stack development",
  "API development",
  "CMS development",
  "mobile app development",
  "app development company",
  "iOS app development",
  "Android app development",
  "cross-platform app development",
  "Flutter app development",
  "React Native development",
  "mobile UI UX design",
  "desktop application development",
  "desktop software development",
  "Windows application development",
  "macOS application development",
  "Electron development",
  "UI UX design",
  "UX design services",
  "user interface design",
  "user experience design",
  "graphic design",
  "branding design",
  "brand identity",
  "logo design",
  "social media design",
  "creative design agency",
  "digital marketing",
  "online marketing",
  "performance marketing",
  "social media marketing",
  "search engine optimization",
  "SEO services",
  "content marketing",
  "marketing strategy",
  "شركة برمجة",
  "شركة تطوير برمجيات",
  "خدمات رقمية",
  "حلول رقمية",
  "تصميم موقع الكتروني",
  "انشاء موقع الكتروني",
  "تطوير موقع الكتروني",
  "تصميم مواقع",
  "برمجة مواقع",
  "متجر الكتروني",
  "انشاء متجر الكتروني",
  "تصميم متجر الكتروني",
  "تطبيق ويب",
  "برمجة ويب ابلكيشن",
  "لوحة تحكم",
  "انشاء تطبيق موبايل",
  "برمجة تطبيقات",
  "تصميم تطبيق موبايل",
  "تطبيق اندرويد",
  "تطبيق ايفون",
  "تطبيقات هجينة",
  "تطبيق سطح مكتب",
  "برنامج كمبيوتر",
  "برنامج ويندوز",
  "تصميم واجهات المستخدم",
  "تجربة المستخدم",
  "جرافيك ديزاين",
  "تصميم جرافيك",
  "تصميم هوية بصرية",
  "تصميم لوجو",
  "تصميم سوشيال ميديا",
  "تسويق الكتروني",
  "تسويق رقمي",
  "ادارة حملات اعلانية",
  "تحسين محركات البحث",
  "خدمات SEO",
];

export const servicesKeywords = [
  ...siteKeywords,
  "website redesign",
  "product design",
  "app maintenance",
  "technical support",
  "software consulting",
  "startup MVP development",
  "branding agency",
];

export const webKeywords = [
  "web development services",
  "custom website development",
  "responsive website design",
  "e-commerce website development",
  "landing page development",
  "web app development",
  "dashboard development",
  "portal development",
  "تطوير الويب",
  "تصميم مواقع احترافية",
  "برمجة مواقع الشركات",
  "برمجة متجر الكتروني",
];

export const mobileKeywords = [
  "mobile development services",
  "mobile app design",
  "native mobile apps",
  "cross-platform mobile apps",
  "Flutter development",
  "React Native apps",
  "Android and iPhone apps",
  "تطوير تطبيقات الجوال",
  "برمجة تطبيق اندرويد",
  "برمجة تطبيق ايفون",
  "تصميم تطبيقات الجوال",
];

export const desktopKeywords = [
  "desktop development services",
  "desktop app development",
  "desktop software",
  "Windows desktop apps",
  "macOS desktop apps",
  "Electron desktop apps",
  "offline desktop software",
  "تطوير تطبيقات سطح المكتب",
  "برمجة برامج كمبيوتر",
  "برامج ويندوز",
  "تطبيقات ديسكتوب",
];
